# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту, если сборка упала
notifications:
  email:
    recipients:
      -envereskendarov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

services:
  - postgresql

before_install:
  - psql -c 'create database rabbit;' -U postgres

env:
  global:
    - CODECOV_TOKEN='e0d386e6-6d16-4bf0-a8fd-ed708788e50e'
